"use client";

import { useEffect, useRef, useState } from "react";

const MERMAID_SRC = "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js";

let loadPromise = null;
function loadMermaid() {
  if (typeof window === "undefined") return Promise.resolve(null);
  if (window.mermaid) return Promise.resolve(window.mermaid);
  if (loadPromise) return loadPromise;
  loadPromise = new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = MERMAID_SRC;
    script.async = true;
    script.onload = () => {
      try {
        window.mermaid?.initialize({
          startOnLoad: false,
          theme: "dark",
          securityLevel: "strict",
          themeVariables: {
            primaryColor: "#0a0f1f",
            primaryTextColor: "#e7ecff",
            primaryBorderColor: "#00b3ff",
            lineColor: "#39ff14",
            tertiaryColor: "#0f1626",
          },
        });
      } catch {
        // ignore
      }
      resolve(window.mermaid || null);
    };
    script.onerror = () => resolve(null);
    document.head.appendChild(script);
  });
  return loadPromise;
}

/**
 * Renders a Mermaid graph from a string. Mermaid runs in `securityLevel: "strict"`
 * which blocks raw HTML in nodes. We additionally strip tags from input.
 * Output is SVG generated by Mermaid.
 */
export function MermaidView({ chart }) {
  const ref = useRef(null);
  const [err, setErr] = useState(null);
  const [svg, setSvg] = useState("");

  useEffect(() => {
    let cancelled = false;
    setErr(null);
    setSvg("");
    if (!chart || typeof chart !== "string") return;
    const cleaned = chart
      .replace(/<\/?[^>]+>/g, "")
      .replace(/javascript:/gi, "")
      .trim();
    if (!cleaned) return;
    (async () => {
      const mermaid = await loadMermaid();
      if (cancelled) return;
      if (!mermaid) {
        setErr("Mermaid failed to load.");
        return;
      }
      try {
        const id = `m-${Math.random().toString(36).slice(2)}`;
        const out = await mermaid.render(id, cleaned);
        if (!cancelled) setSvg(typeof out === "string" ? out : out?.svg || "");
      } catch (e) {
        if (!cancelled) setErr(e?.message || "Failed to render diagram.");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [chart]);

  if (err) {
    return (
      <pre className="card overflow-auto text-xs text-ink-dim whitespace-pre-wrap">
        Diagram render failed: {err}
        {"\n\nSource:\n"}
        {chart}
      </pre>
    );
  }
  return (
    <div
      ref={ref}
      className="card overflow-auto"
      // svg produced by Mermaid (securityLevel: strict)
      dangerouslySetInnerHTML={{ __html: svg || '<div class="text-ink-dim text-sm">Rendering…</div>' }}
    />
  );
}
